server:
  port: 6666
  servlet:
    context-path: /invest/api
spring:
  application:
    name: invest-project
  datasource:
    url: jdbc:mysql://localhost:3306/invest?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: admin